#!/bin/bash

# yopush
# upload yeoman ./dist directory to host, using basename of parent directory as default dest path
# cjb 2016-10-25

REMOTEHOST="oqsweb.ndph.ox.ac.uk"
REMOTEUSER="cp"
REMOTEROOT="/user/cp/public_html/bbquiz/"  # http://red.ctsu.ox.ac.uk/~cp/cjb/
REMOTEDIR="$(basename "$(dirname "$(pwd)")")"

if [ ! -e app/index.html ]
then
    #echo $(basename $(dirname $(pwd))) " does not look like a yeoman directory, exiting"
    echo $(pwd)" does not look like a yeoman directory, exiting"
    exit 0
fi

if [ -z "$1" ] # if $1 is zero length!
then
    read -p "Remote host (oqsweb, red, wf)? [$REMOTEHOST]  " answer;    # -n1 restrict to 1 char -r raw -s silent (password)
    # PS3='Remote host? [$REMOTEHOST]'; 
    # select answer in oqsweb red wf; 
    # do 
    #     echo $answer
    #     break;
    # done
else
    answer=$1;
fi

case $answer in
    oqsweb)
        REMOTEHOST="oqsweb.ndph.ox.ac.uk";;
    red)
        REMOTEHOST="red.ctsu.ox.ac.uk"
        REMOTEROOT="/user/cp/public_html/cjb/bbquiz/";;
    wf)
        REMOTEHOST="web456.webfaction.com"
        REMOTEUSER="drkvogel"
        REMOTEROOT="/home/drkvogel/webapps/main/bbquiz/"
        ;;
    '')
        ;;  # default
    *)  
        echo "Unknown host, exiting"
        exit;;
esac

#echo "option: $answer"
REMOTEPATH=$REMOTEROOT$REMOTEDIR
##read -p 'Continue (y/n)? ' -n1 answer; echo; [[ $answer = [yY] ]] || exit

echo "Remember to run gulp first to build into ./dist"
echo "Copying to $REMOTEUSER@$REMOTEHOST:$REMOTEPATH"
#echo "($REMOTEPATH must exist on server already?)"
read -rsp $'Press any key to continue...\n' -n1 key
rsync -r --info=progress2 -e ssh ./dist/* $REMOTEUSER@$REMOTEHOST:$REMOTEPATH
#scp -r ./dist/* $REMOTEUSER@$REMOTEHOST:$REMOTEPATH
exit 0

#do [[ $answer = oqsweb ]] && { echo Correct; break; } || echo Try again; done